//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyKhachSan
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_DatPhong
    {
        public string IDThueP { get; set; }
        public string IDPhong { get; set; }
        public string IDKH { get; set; }
        public Nullable<System.DateTime> NgayDat { get; set; }
        public Nullable<int> SoNguoi { get; set; }
    }
}
