//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyKhachSan
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_DichVu
    {
        public string IDDV { get; set; }
        public string TenDV { get; set; }
        public Nullable<double> Gia { get; set; }
        public string LoaiDV { get; set; }
    }
}
