//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyKhachSan
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_HoaDon
    {
        public string IDHoaDon { get; set; }
        public string IDNV { get; set; }
        public string IDKH { get; set; }
        public string Note { get; set; }
        public Nullable<double> TongTien { get; set; }
        public Nullable<System.DateTime> NgayThanhToan { get; set; }
    }
}
