//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyKhachSan
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_LoaiPhong
    {
        public int IDLoaiP { get; set; }
        public string TenLoaiP { get; set; }
        public Nullable<double> Gia { get; set; }
        public Nullable<int> SoGiuong { get; set; }
        public Nullable<int> SoNguoi { get; set; }
    }
}
