//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyKhachSan
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Phong
    {
        public string IDPhong { get; set; }
        public string TenP { get; set; }
        public Nullable<int> IDLoaiP { get; set; }
        public Nullable<int> IDTrangThai { get; set; }
    }
}
